export const Products = [
  {
    SKU: '12121',
    Marka: '1',
    Nazwa: '1',
    Kategora: '1',
    Cena: 22,
    Ilosc: 2,
    Status: 'Wystawione',
  },
  {
    SKU: '12121',
    Marka: '2',
    Nazwa: '1',
    Kategora: '1',
    Cena: 22,
    Ilosc: 2,
    Status: 'Wystawione',
  },
  {
    SKU: '12121',
    Marka: '3',
    Nazwa: '1',
    Kategora: '1',
    Cena: 22,
    Ilosc: 2,
    Status: 'Wystawione',
  },
  {
    SKU: '12121',
    Marka: '1',
    Nazwa: '3',
    Kategora: '1',
    Cena: 22,
    Ilosc: 2,
    Status: 'Wystawione',
  },
  {
    SKU: '12121',
    Marka: '1',
    Nazwa: '1',
    Kategora: '1',
    Cena: 22,
    Ilosc: 2,
    Status: 'Wystawione',
  },
  {
    SKU: '12121',
    Marka: '1',
    Nazwa: '1',
    Kategora: '1',
    Cena: 22,
    Ilosc: 2,
    Status: 'Wystawione',
  },
  {
    SKU: '12121',
    Marka: '1',
    Nazwa: '1',
    Kategora: '1',
    Cena: 22,
    Ilosc: 2,
    Status: 'Wystawione',
  },
  {
    SKU: '12121',
    Marka: '1',
    Nazwa: '1',
    Kategora: '1',
    Cena: 22,
    Ilosc: 2,
    Status: 'Wystawione',
  },
  {
    SKU: '12121',
    Marka: '1',
    Nazwa: '1',
    Kategora: '1',
    Cena: 22,
    Ilosc: 2,
    Status: 'Wystawione',
  },
  {
    SKU: '12121',
    Marka: '1',
    Nazwa: '1',
    Kategora: '1',
    Cena: 22,
    Ilosc: 2,
    Status: 'Wystawione',
  },
  {
    SKU: '12121',
    Marka: '1',
    Nazwa: '1',
    Kategora: '1',
    Cena: 22,
    Ilosc: 2,
    Status: 'Wystawione',
  },
];
